# -*- coding: utf-8 -*-
"""NM_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7mcylawylflBcYBvThzr5WQVLxgQByO
"""

import os
import pickle
import streamlit as st
from streamlit_option_menu import option_menu

# Set page configuration
st.set_page_config(page_title="Zaheer's ShifaAI - Health Assistant",
                   layout="wide",
                   page_icon="🧑‍⚕️")

# Get working directory of the script
# working_dir = os.path.dirname(os.path.abspath(__file__)) # This line was causing the error
working_dir = os.getcwd() # This line gets the current working directory

# Load models safely with error handling
def load_model(filename):
    try:
        return pickle.load(open(f'{working_dir}/saved_models/{filename}', 'rb')) # Updated path with working_dir
    except Exception as e:
        st.error(f"Error loading {filename}: {e}")
        return None

diabetes_model = load_model('diabetes_model.sav')
heart_disease_model = load_model('heart_disease_model.sav')
parkinsons_model = load_model('parkinsons_model.sav')

# ... (rest of the code remains the same) ...

# Sidebar for navigation
with st.sidebar:
    selected = option_menu("Zaheer's 👇 \n Shifa - AI \n (Predict Health on your own 😎)",
                           ['Diabetes Prediction', 'Heart Disease Prediction', 'Parkinsons Prediction'],
                           menu_icon='hospital-fill',
                           icons=['activity', 'heart', 'person'],
                           default_index=0)

# ======================== Diabetes Prediction Page ========================
if selected == 'Diabetes Prediction':
    st.title('Diabetes Prediction using ML')

    # Getting user input with proper validation
    col1, col2, col3 = st.columns(3)

    with col1:
        Pregnancies = st.number_input('Number of Pregnancies', min_value=0, max_value=20, step=1)

    with col2:
        Glucose = st.number_input('Glucose Level', min_value=0, max_value=300)

    with col3:
        BloodPressure = st.number_input('Blood Pressure value', min_value=0, max_value=200)

    with col1:
        SkinThickness = st.number_input('Skin Thickness value', min_value=0, max_value=100)

    with col2:
        Insulin = st.number_input('Insulin Level', min_value=0, max_value=1000)

    with col3:
        BMI = st.number_input('BMI value', min_value=0.0, max_value=100.0)

    with col1:
        DiabetesPedigreeFunction = st.number_input('Diabetes Pedigree Function value', min_value=0.0, max_value=2.5)

    with col2:
        Age = st.number_input('Age of the Person', min_value=1, max_value=120)

    diab_diagnosis = ""

    if st.button('Check Diabetes Result'):
        if diabetes_model is not None:
            user_input = [[Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]]
            prediction = diabetes_model.predict(user_input)
            diab_diagnosis = "The person is diabetic" if prediction[0] == 1 else "The person is not diabetic"
        else:
            diab_diagnosis = "Error: Model not loaded."

    st.success(diab_diagnosis)

# ======================== Heart Disease Prediction Page ========================
if selected == 'Heart Disease Prediction':
    st.title('Heart Disease Prediction using ML')

    col1, col2, col3 = st.columns(3)

    with col1:
        age = st.number_input('Age', min_value=1, max_value=120)

    with col2:
        sex = st.radio('Sex', options=[0, 1], format_func=lambda x: "Male" if x == 1 else "Female")

    with col3:
        cp = st.number_input('Chest Pain types', min_value=0, max_value=3)

    with col1:
        trestbps = st.number_input('Resting Blood Pressure', min_value=80, max_value=200)

    with col2:
        chol = st.number_input('Serum Cholesterol in mg/dl', min_value=100, max_value=600)

    with col3:
        fbs = st.radio('Fasting Blood Sugar > 120 mg/dl', options=[0, 1])

    with col1:
        restecg = st.number_input('Resting Electrocardiographic results', min_value=0, max_value=2)

    with col2:
        thalach = st.number_input('Maximum Heart Rate achieved', min_value=60, max_value=220)

    with col3:
        exang = st.radio('Exercise Induced Angina', options=[0, 1])

    with col1:
        oldpeak = st.number_input('ST depression induced by exercise', min_value=0.0, max_value=6.2)

    with col2:
        slope = st.number_input('Slope of the peak exercise ST segment', min_value=0, max_value=2)

    with col3:
        ca = st.number_input('Major vessels colored by fluoroscopy', min_value=0, max_value=4)

    with col1:
        thal = st.number_input('Thal (0=normal, 1=fixed defect, 2=reversible defect)', min_value=0, max_value=3)

    heart_diagnosis = ""

    if st.button('Check Heart Disease Result'):
        if heart_disease_model is not None:
            user_input = [[age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]]
            prediction = heart_disease_model.predict(user_input)
            heart_diagnosis = "The person has heart disease" if prediction[0] == 1 else "The person does not have heart disease"
        else:
            heart_diagnosis = "Error: Model not loaded."

    st.success(heart_diagnosis)

# ======================== Parkinson's Prediction Page ========================
if selected == "Parkinsons Prediction":
    st.title("Parkinson's Disease Prediction using ML")

    features = ["MDVP:Fo(Hz)", "MDVP:Fhi(Hz)", "MDVP:Flo(Hz)", "MDVP:Jitter(%)", "MDVP:Jitter(Abs)", "MDVP:RAP",
                "MDVP:PPQ", "Jitter:DDP", "MDVP:Shimmer", "MDVP:Shimmer(dB)", "Shimmer:APQ3", "Shimmer:APQ5",
                "MDVP:APQ", "Shimmer:DDA", "NHR", "HNR", "RPDE", "DFA", "spread1", "spread2", "D2", "PPE"]

    user_inputs = []
    for feature in features:
        user_inputs.append(st.number_input(feature, format="%.6f"))

    parkinsons_diagnosis = ""

    if st.button("Check Parkinson's Result"):
        if parkinsons_model is not None:
            prediction = parkinsons_model.predict([user_inputs])
            parkinsons_diagnosis = "The person has Parkinson's disease" if prediction[0] == 1 else "The person does not have Parkinson's disease"
        else:
            parkinsons_diagnosis = "Error: Model not loaded."

    st.success(parkinsons_diagnosis)

